import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import QueryWrapper from "@/components/react-query/query-wrapper";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "@/components/common/theme-provider";

const roboto = Roboto({
    subsets: [
        "latin",
        "cyrillic",
        "greek",
        "cyrillic-ext",
        "greek-ext",
        "latin-ext",
        "vietnamese",
    ],
    weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
    title: "BlogDev",
    description: "Generated by Duy Phan",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={roboto.className}>
                <NextTopLoader />
                <QueryWrapper>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                </QueryWrapper>
            </body>
        </html>
    );
}
